name: DEPLOY NO S3

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.21.0
      - name: Install AWS
        run: pip install awscli
      - name: Install e build
        run: npm install && npm run build
        env:
            CI: "false"
      - name: Deploy AWS
        run: cd build && AWS_ACCESS_KEY_ID=${CHAVE} AWS_SECRET_ACCESS_KEY=${SENHA} aws s3 sync . s3://treinazap --acl public-read --delete
        env:
           CHAVE: ${{ secrets.ACCESS_KEY }}
           SENHA: ${{ secrets.SECRET_KEY }}
